kind: "API"
version: "1"
metadata:
  envTypes: ["dev", "stage", "prod"]
data:
  allowedClientIDs:
    author:
      - "aem-oauth-chatgpt"
      - "aem-oauth-claude"
      - "aem-oauth-mscopilot"
      - "aem-oauth-cursor"